import { NextResponse } from "next/server";
import { compactJson,createStructuredJson } from "@/lib/ai/core";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export const dynamic="force-dynamic";
const schema={type:"object",required:["overall_score","verdict","audience_fit","positioning_alignment","capability_relevance","market_relevance","claim_compliance","strengths","misalignments","recommendations"],properties:{overall_score:{type:"number",minimum:0,maximum:100},verdict:{type:"string"},audience_fit:{type:"number",minimum:0,maximum:100},positioning_alignment:{type:"number",minimum:0,maximum:100},capability_relevance:{type:"number",minimum:0,maximum:100},market_relevance:{type:"number",minimum:0,maximum:100},claim_compliance:{type:"number",minimum:0,maximum:100},strengths:{type:"array",items:{type:"string"}},misalignments:{type:"array",items:{type:"string"}},recommendations:{type:"array",items:{type:"string"}}}};
function errorJson(message:string,status=400){return NextResponse.json({ok:false,error:message},{status})}
function sameOrigin(request:Request){const origin=request.headers.get("origin");const host=request.headers.get("x-forwarded-host")||request.headers.get("host");if(!origin||!host)return true;try{return new URL(origin).host===host}catch{return false}}
async function requireSessionIfConfigured(){if(!process.env.NEXT_PUBLIC_SUPABASE_URL||!process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)return true;const supabase=await createServerSupabaseClient();const{data:{user}}=await supabase.auth.getUser();return Boolean(user)}
export async function POST(request:Request){try{if(!sameOrigin(request))return errorJson("Cross-origin request ditolak.",403);if(!(await requireSessionIfConfigured()))return errorJson("Session login tidak valid.",401);const body=await request.json().catch(()=>({}));if(!body?.brief||!body?.brandIntelligence)return errorJson("Full Brief dan Brand Intelligence wajib tersedia.");const result=await createStructuredJson<any>({schema: schema as Record<string,unknown>,system:"Kamu adalah senior brand strategist dan editorial QA reviewer. Nilai alignment konten dengan Brand Intelligence, bukan sekadar kualitas tulisan.",user:`BRAND INTELLIGENCE:\n${compactJson(body.brandIntelligence)}\n\nCONTENT BRIEF:\n${compactJson(body.brief)}\n\nNilai dengan bobot Audience Fit 25%, Positioning Alignment 25%, Capability Relevance 20%, Market Relevance 15%, Claim Compliance 15%. Jangan memberi nilai tinggi hanya karena nama brand disebut. Penalti capability/claim yang tidak didukung Brand Intelligence atau melanggar prohibited_claims. Case-led storytelling boleh menunda brand bridge sampai akhir. Jika Brand Intelligence kurang lengkap, jangan mengarang standar brand. Recommendations harus actionable dan menunjuk bagian brief. Semua output Bahasa Indonesia.`,temperature:0.15});return NextResponse.json({ok:true,data:result})}catch(error){console.error("brand-alignment error",error);return errorJson(error instanceof Error?error.message:"Brand Alignment QC gagal.",500)}}
