"use client";
import {useEffect,useMemo,useState} from "react";
import {CalendarDays,CheckCircle2,Clock3,Palette,RotateCcw} from "lucide-react";
import {loadAllBriefs,type BriefRecord} from "@/lib/smm-workflow";
import {loadExpansionCalendarItems} from "@/lib/expansion-calendar";
import {loadBrands,loadTasks} from "@/lib/workspace-store";
import {useActiveBrand} from "@/components/active-brand";

type Item={id:string;brandId:string;brandName:string;title:string;channel:"social"|"linkedin"|"seo_geo";scheduledFor?:string;humanQc:"pending"|"approved";designStatus?:string;href:string;updatedAt?:string};
function social(b:BriefRecord):Item{return{id:b.id,brandId:b.brand_id||"",brandName:b.brand_name||"Brand",title:b.working_title||"Untitled",channel:"social",scheduledFor:b.scheduled_for,humanQc:b.human_qc,designStatus:b.production_status,href:`/brief/${b.id}`,updatedAt:b.updated_at}}
const label=(c:Item["channel"])=>c==="linkedin"?"LINKEDIN":c==="seo_geo"?"SEO/GEO":"SOCIAL";
export function ProductionOverview(){const {activeBrand}=useActiveBrand();const [scope,setScope]=useState<string>(activeBrand.id);const [tick,setTick]=useState(0);useEffect(()=>setScope(activeBrand.id),[activeBrand.id]);useEffect(()=>{const fn=()=>setTick(x=>x+1);window.addEventListener("storage",fn);window.addEventListener("focus",fn);window.addEventListener("proxsis-workspace:updated",fn as EventListener);return()=>{window.removeEventListener("storage",fn);window.removeEventListener("focus",fn);window.removeEventListener("proxsis-workspace:updated",fn as EventListener)}},[]);
 const data=useMemo(()=>{void tick;const briefs=loadAllBriefs().map(social);const expansion=loadExpansionCalendarItems().map(x=>({id:x.id,brandId:x.brand_id||"",brandName:x.brand_name,title:x.title,channel:x.channel,scheduledFor:x.scheduled_for,humanQc:"approved" as const,href:`/brief/${x.brief_id}/expansion/${x.channel}`}));return[...briefs,...expansion]},[tick]);const brands=useMemo(()=>loadBrands(),[tick]);const scoped=scope==="__all__"?data:data.filter(x=>x.brandId===scope);const socialOnly=scoped.filter(x=>x.channel==="social");const draft=socialOnly.filter(x=>x.humanQc!=="approved").length;const final=socialOnly.filter(x=>x.humanQc==="approved").length;const revision=socialOnly.filter(x=>x.humanQc==="pending"&&x.updatedAt).length;const waiting=socialOnly.filter(x=>x.humanQc==="approved"&&x.designStatus!=="designed").length;const designed=socialOnly.filter(x=>x.designStatus==="designed").length;const today=new Date().toISOString().slice(0,10);const upcoming=scoped.filter(x=>x.scheduledFor&&x.scheduledFor>=today).sort((a,b)=>String(a.scheduledFor).localeCompare(String(b.scheduledFor))).slice(0,8);const attention=socialOnly.filter(x=>x.humanQc!=="approved"||(x.humanQc==="approved"&&x.designStatus!=="designed")).slice(0,8);const tasks=loadTasks();const openTasks=(scope==="__all__"?tasks:tasks.filter(t=>t.brand_id===scope)).filter(t=>t.status!=="done").length;
 return <section className="panel" style={{padding:22}}><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"end",flexWrap:"wrap"}}><div><p className="eyebrow">PRODUCTION COMMAND CENTER</p><h2 style={{fontSize:26,margin:"4px 0"}}>Content Production Overview</h2><p className="muted">Pantau brief, QC, design handoff, task, dan jadwal lintas channel dari satu tempat.</p></div><select className="period" value={scope} onChange={e=>setScope(e.target.value)}><option value="__all__">All Brands</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>
 <div className="metric-grid" style={{marginTop:18}}>{[["Draft Brief",draft],["Final Brief",final],["Perlu Revisi",revision],["Ready to Design",waiting],["Designed",designed],["Open Tasks",openTasks]].map(([k,v])=><div className="metric" key={String(k)}><span>{k}</span><strong>{v}</strong><em>{scope==="__all__"?"All Brands":"Current scope"}</em></div>)}</div>
 <div className="panel" style={{marginTop:18,padding:18}}><div className="panel-head"><div><h2>Production Pipeline</h2><p>Draft → Revision → Final → Ready to Design → Designed</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(0,1fr))",gap:10}}>{[["Draft",draft,Clock3],["Revision",revision,RotateCcw],["Final",final,CheckCircle2],["Ready to Design",waiting,Palette],["Designed",designed,CheckCircle2]].map(([name,value,Icon]:any)=><div key={name} style={{border:"1px solid #ebe4e6",borderRadius:12,padding:14,background:"#fff"}}><Icon size={18}/><b style={{display:"block",fontSize:22,marginTop:8}}>{value}</b><span style={{fontSize:12,color:"#756b70"}}>{name}</span></div>)}</div></div>
 <div className="grid-two" style={{marginTop:18}}><section className="panel"><div className="panel-head"><div><h2>Needs Attention</h2><p>QC ulang atau menunggu design</p></div></div><div className="rows">{attention.length?attention.map(x=><a className="row" href={x.href} key={x.id} style={{textDecoration:"none",color:"inherit"}}><span className="rank">!</span><div><b>{x.title}</b><small>{x.brandName} · {label(x.channel)}</small></div><strong>{x.humanQc==="approved"?"DESIGN":"QC"}</strong></a>):<p className="muted">Tidak ada item yang membutuhkan tindakan.</p>}</div></section><section className="panel"><div className="panel-head"><div><h2>Upcoming Content</h2><p>Jadwal terdekat</p></div><a className="ghost" href="/?section=Content%20Calendar">Calendar</a></div><div className="rows">{upcoming.length?upcoming.map(x=><a className="row" href={x.href} key={x.id} style={{textDecoration:"none",color:"inherit"}}><CalendarDays size={18}/><div><b>{x.title}</b><small>{x.brandName} · {label(x.channel)}</small></div><strong>{x.scheduledFor}</strong></a>):<p className="muted">Belum ada content mendatang.</p>}</div></section></div>
 {scope==="__all__"&&<section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Brand Breakdown</h2><p>Production workload per brand</p></div></div><div className="rows">{brands.map(b=>{const items=data.filter(x=>x.brandId===b.id);const finals=items.filter(x=>x.humanQc==="approved").length;const scheduled=items.filter(x=>x.scheduledFor).length;return <div className="row" key={b.id}><span className="rank">{items.length}</span><div><b>{b.name}</b><small>{finals} final · {scheduled} scheduled</small></div><strong>{items.filter(x=>x.channel!=="social").length} derivative</strong></div>})}</div></section>}
 </section>}
