import { NextResponse } from "next/server";
import { average, clampScore, compactJson, createStructuredJson, loadStorytellingKnowledge } from "@/lib/ai/core";
import { angleSynthesisSchema, queryPlanSchema } from "@/lib/ai/schemas";
import { normalizeSources, tavilySearch } from "@/lib/ai/tavily";
import type { BrandIntelligence } from "@/lib/types";

export const maxDuration = 300;
export const dynamic = "force-dynamic";

type QuickBrief = { brandId?:string; brandName:string; website?:string; topic:string; audience:string; objective:string; cta?:string; preferredFormat?:"auto"|"carousel"|"reels"|"single_post"; extraContext?:string; brandIntelligence?:BrandIntelligence|null };
type QueryPlan={queries:string[]};
type Synthesis={brand_profile:{positioning:string;value_proposition:string;audience_pain_points:string[];tone_of_voice:string;key_messages:string[];brand_pov:string;core_expertise:string[];communication_dos:string[];communication_donts:string[]};campaign:{desired_perception:string;business_problem:string;key_message:string;funnel_stage:"awareness"|"consideration"|"conversion"};cases:Array<{key:string;company_name:string;case_title:string;case_summary:string;business_problem:string;tension:string;decision_or_move:string;mechanism:string;outcome:string;executive_implication:string;topic_relevance_score:number;campaign_alignment_score:number;relevance_score:number;credibility_score:number;tension_score:number;executive_value_score:number;brand_fit_score:number;confidence:"low"|"medium"|"high";sources:Array<{ref:string;source_type:string;fact_notes:string}>}>;ideas:Array<{case_key:string;working_title:string;content_angle:string;tension:string;core_insight:string;recommended_format:"carousel"|"reels"|"single_post";campaign_relevance:string}>};

function errorJson(message:string,status=400){return NextResponse.json({ok:false,error:message},{status})}
function sameOrigin(request:Request){const origin=request.headers.get("origin");const host=request.headers.get("x-forwarded-host")||request.headers.get("host");if(!origin||!host)return true;try{return new URL(origin).host===host}catch{return false}}
function formatLabel(format:QuickBrief["preferredFormat"]){if(format==="carousel")return"Utamakan carousel.";if(format==="reels")return"Utamakan Reels.";if(format==="single_post")return"Utamakan single post.";return"Pilih format terbaik per angle berdasarkan kekuatan cerita."}
function envDiagnostic(){const env=process.env.VERCEL_ENV||"unknown";const deployment=process.env.VERCEL_URL||process.env.VERCEL_PROJECT_PRODUCTION_URL||"unknown-deployment";const deepseek=Boolean(process.env.DEEPSEEK_API_KEY?.trim());const tavily=Boolean(process.env.TAVILY_API_KEY?.trim());return `env=${env}; deployment=${deployment}; DEEPSEEK_API_KEY=${deepseek?"available":"missing"}; TAVILY_API_KEY=${tavily?"available":"missing"}`}

export async function POST(request:Request){
 try{
  if(!sameOrigin(request))return errorJson("Cross-origin request ditolak.",403);
  const body=(await request.json().catch(()=>({}))) as Partial<QuickBrief>;
  const input:QuickBrief={brandId:String(body.brandId??"").trim(),brandName:String(body.brandName??"").trim(),website:String(body.website??"").trim(),topic:String(body.topic??"").trim(),audience:String(body.audience??"").trim(),objective:String(body.objective??"").trim(),cta:String(body.cta??"").trim(),preferredFormat:body.preferredFormat??"auto",extraContext:String(body.extraContext??"").trim(),brandIntelligence:body.brandIntelligence??null};
  if(!input.brandName||!input.topic||!input.audience||!input.objective)return errorJson("Brand, topik/program, target audience, dan objective wajib terisi.");
  if(!process.env.DEEPSEEK_API_KEY?.trim())return errorJson(`DEEPSEEK_API_KEY belum tersedia pada deployment ini. ${envDiagnostic()}`,503);
  if(!process.env.TAVILY_API_KEY?.trim())return errorJson(`TAVILY_API_KEY belum tersedia pada deployment ini. ${envDiagnostic()}`,503);

  const knowledge=await loadStorytellingKnowledge();
  const today=new Date().toISOString().slice(0,10);
  const queryPlan=await createStructuredJson<QueryPlan>({schema:queryPlanSchema as unknown as Record<string,unknown>,system:"Kamu adalah search strategist untuk riset case study B2B. Buat query yang menemukan peristiwa nyata, keputusan, konflik, dan mekanisme. Jika exact-match case langka, cari analogous case yang memiliki business mechanism, decision pattern, atau transformation challenge yang sama.",user:`TANGGAL: ${today}\n\nTOPIC LOCK — HARD CONSTRAINT:\n${input.topic}\n\nQUICK CAMPAIGN BRIEF:\n${compactJson(input)}\n\nBuat tepat 4 query web dengan strategi bertingkat:\n1) exact/direct case yang paling dekat dengan TOPIC LOCK,\n2) berita/peristiwa atau strategic tension terbaru yang terkait langsung,\n3) analogous case dari industri/perusahaan lain dengan mechanism atau decision pattern yang sama,\n4) benchmark implementation/turnaround/successful response yang dapat ditarik insight-nya ke TOPIC LOCK.\n\nAnalogous case BOLEH berbeda industri atau istilah selama hubungan mekanismenya jelas dan dapat dijelaskan secara eksplisit. Jangan sekadar mencari expertise brand. Prioritas evidence: official/company/regulator, reputable business media, research, atau academic source. Cari nama perusahaan/organisasi, kejadian konkret, konsekuensi, keputusan, dan mechanism.`,temperature:0.15});
  const queries=(queryPlan.queries??[]).map(q=>q.trim()).filter(Boolean).slice(0,4);
  if(queries.length<4)return errorJson("AI gagal membuat search query yang cukup.",502);
  const batches=await Promise.all(queries.map(async query=>({query,results:await tavilySearch(query)})));
  const webSources=normalizeSources(batches);
  if(webSources.length<3)return errorJson("Source live research terlalu sedikit untuk membuat angle yang dapat dipertanggungjawabkan. Coba generate ulang atau tambahkan konteks.",502);
  const sourceCatalog=webSources.map(s=>`${s.ref} | ${s.publisher} | ${s.title} | ${s.url}\nSNIPPET: ${s.content}`).join("\n\n");

  const synthesis=await createStructuredJson<Synthesis>({schema:angleSynthesisSchema as unknown as Record<string,unknown>,system:"Kamu adalah senior B2B researcher, news analyst, content strategist, dan executive storyteller. Semua output human-facing Bahasa Indonesia. Tolak konten generik dan AI slop. Exact case lebih disukai, tetapi analogous case yang kuat diperbolehkan bila mekanisme relevansinya dijelaskan dengan jelas.",user:`EDITORIAL KNOWLEDGE BASE:\n${knowledge}\n\nTOPIC LOCK — USER REQUEST:\n${input.topic}\n\nQUICK INPUT:\n${compactJson(input)}\n\nACTIVE BRAND INTELLIGENCE — hanya guardrail HOW, jangan mengganti WHAT/topik:\n${compactJson(input.brandIntelligence)}\n\nPRIORITAS: 1) topic user, 2) audience + objective, 3) evidence live, 4) brand POV/tone/capability guardrail.\n\nLIVE WEB SOURCES — fakta hanya dari katalog ini:\n${sourceCatalog}\n\nTUGAS:\n1. Turunkan campaign logic.\n2. Pilih 1-4 kasus nyata dengan tension + mechanism kuat. Exact-match case diprioritaskan, tetapi jika evidence exact terbatas gunakan analogous case yang memiliki mechanism, decision pattern, transformation challenge, atau business consequence yang serupa.\n3. Untuk analogous case, jelaskan hubungan logisnya ke TOPIC LOCK di case_summary/executive_implication; jangan mengklaim kasus itu identik.\n4. Buat tepat 5 Story Angles berbeda secara editorial, bukan variasi judul. Satu kasus yang kuat BOLEH menjadi dasar beberapa angle selama tension, mechanism, atau executive insight-nya benar-benar berbeda.\n5. Utamakan newsworthy/recent case bila evidence cukup; benchmark lama boleh dipakai bila mechanism jauh lebih kuat.\n\nSCORING: untuk exact case, target topic_relevance_score >=7. Untuk analogous case yang mechanism-nya kuat, score 6 masih boleh bila campaign_alignment_score >=7 dan hubungan ke topik dijelaskan eksplisit. Jangan menaikkan score hanya karena brand fit.\n\nATURAN STORYTELLING: Case/Evidence → Tension → Mechanism → Insight → Brand POV → Audience Relevance. Hook spesifik dan curiosity-driving, bukan clickbait. Jangan membuat angka, quote, motive, legal finding, atau sebab-akibat tanpa source. Audience: ${input.audience}. ${formatLabel(input.preferredFormat)} Extra context: ${input.extraContext||"Tidak ada."}`,temperature:0.28});

  const sourceMap=new Map(webSources.map(source=>[source.ref,source]));
  const cases=synthesis.cases.map(item=>{const mapped=item.sources.map(source=>({...source,source:sourceMap.get(source.ref)})).filter(row=>Boolean(row.source));const score=average([clampScore(item.relevance_score),clampScore(item.credibility_score),clampScore(item.tension_score),clampScore(item.executive_value_score),clampScore(item.brand_fit_score)]);return{id:crypto.randomUUID(),...item,score,mapped_sources:mapped.map(row=>({ref:row.ref,source_type:row.source_type,fact_notes:row.fact_notes,publisher:row.source!.publisher,title:row.source!.title,url:row.source!.url})),selected:false}});
  const strongCases=cases.filter(item=>item.mapped_sources.length>=1&&item.confidence!=="low"&&clampScore(item.topic_relevance_score)>=7&&clampScore(item.campaign_alignment_score)>=7);
  const analogousCases=cases.filter(item=>item.mapped_sources.length>=1&&item.confidence!=="low"&&clampScore(item.topic_relevance_score)>=6&&clampScore(item.campaign_alignment_score)>=7);
  const eligible=strongCases.length>0?strongCases:analogousCases.length>0?analogousCases:cases.filter(item=>item.mapped_sources.length>=1&&item.confidence!=="low");
  if(eligible.length<1)return errorJson(`Belum ditemukan kasus dengan evidence yang cukup untuk topik “${input.topic}”. Coba generate ulang atau tambahkan konteks.`,502);
  const best=[...eligible].sort((a,b)=>average([b.score,clampScore(b.topic_relevance_score),clampScore(b.campaign_alignment_score)])-average([a.score,clampScore(a.topic_relevance_score),clampScore(a.campaign_alignment_score)]))[0];
  cases.forEach(item=>{item.selected=item.id===best.id});
  const caseByKey=new Map(eligible.map(item=>[item.key,item]));
  const ideas=synthesis.ideas.slice(0,5).map((idea,index)=>{const researchCase=caseByKey.get(idea.case_key)||best;const preferred=input.preferredFormat&&input.preferredFormat!=="auto"?input.preferredFormat:idea.recommended_format;return{id:crypto.randomUUID(),index:index+1,research_case_id:researchCase.id,working_title:idea.working_title,content_angle:idea.content_angle,tension:idea.tension,core_insight:idea.core_insight,recommended_format:preferred,campaign_relevance:idea.campaign_relevance,status:"idea"}});
  if(ideas.length!==5)return errorJson("AI tidak mengembalikan tepat 5 Story Angles.",502);
  const campaignId=crypto.randomUUID();
  return NextResponse.json({ok:true,campaignId,campaign:{id:campaignId,brand_id:input.brandId||null,brand_name:input.brandName,website:input.website||"",topic:input.topic,objective:input.objective,audience:input.audience,cta:input.cta||"",preferred_format:input.preferredFormat||"auto",desired_perception:synthesis.campaign.desired_perception,business_problem:synthesis.campaign.business_problem,key_message:synthesis.campaign.key_message,funnel_stage:synthesis.campaign.funnel_stage,created_at:new Date().toISOString()},brand_profile:synthesis.brand_profile,cases,ideas,sources:webSources,queries});
 }catch(error){console.error("Story angles error",error);return errorJson(error instanceof Error?error.message:"Gagal menghasilkan storytelling angles.",500)}
}
