"use client";

import { useMemo,useState } from "react";
import { BarChart3,Brain,CalendarDays,FileText,Gauge,Instagram,LayoutDashboard,ListTodo,Megaphone,Menu,Search,Settings,ShieldCheck,Sparkles,Users,X } from "lucide-react";
import { useActiveBrand } from "@/components/active-brand";
import { AudienceAnalytics,BrandIntelligence,CompetitorBenchmarking,ContentCalendar,ContentPerformance,PostingSchedule,Reports,TeamTasks,UsersAccess,WorkspaceHub } from "@/components/dashboard";

type Section="Overview"|"Brand Intelligence"|"Brief Studio"|"Content Performance"|"Audience Analytics"|"Posting Schedule"|"Competitor Benchmarking"|"Content Calendar"|"Team Tasks"|"Workspace Hub"|"Reports"|"Users & Access";
const sections:{name:Section;icon:React.ReactNode}[]=[
{name:"Overview",icon:<LayoutDashboard size={18}/>},{name:"Brand Intelligence",icon:<Brain size={18}/>},{name:"Brief Studio",icon:<Sparkles size={18}/>},{name:"Content Performance",icon:<BarChart3 size={18}/>},{name:"Audience Analytics",icon:<Users size={18}/>},{name:"Posting Schedule",icon:<CalendarDays size={18}/>},{name:"Competitor Benchmarking",icon:<Gauge size={18}/>},{name:"Content Calendar",icon:<CalendarDays size={18}/>},{name:"Team Tasks",icon:<ListTodo size={18}/>},{name:"Workspace Hub",icon:<Megaphone size={18}/>},{name:"Reports",icon:<FileText size={18}/>},{name:"Users & Access",icon:<ShieldCheck size={18}/>},
];

export default function Home(){
 const[active,setActive]=useState<Section>("Overview");const[open,setOpen]=useState(false);const[period,setPeriod]=useState("Last 30 Days");const{activeBrand,brands,setActiveBrandId}=useActiveBrand();
 const cards=useMemo(()=>[["Total Views","1.24M","+18.4%"],["Accounts Reached","382.6K","+12.7%"],["Interactions","21.8K","+9.3%"],["Profile Visits","14.2K","+7.8%"]],[]);
 const render=()=>{
  if(active==="Brand Intelligence")return <BrandIntelligence/>;if(active==="Content Performance")return <ContentPerformance/>;if(active==="Audience Analytics")return <AudienceAnalytics/>;if(active==="Posting Schedule")return <PostingSchedule/>;if(active==="Competitor Benchmarking")return <CompetitorBenchmarking/>;if(active==="Content Calendar")return <ContentCalendar/>;if(active==="Team Tasks")return <TeamTasks/>;if(active==="Workspace Hub")return <WorkspaceHub/>;if(active==="Reports")return <Reports/>;if(active==="Users & Access")return <UsersAccess/>;
  if(active==="Brief Studio")return <section className="panel empty-panel"><div className="empty-icon"><Sparkles size={22}/></div><h2>Brief Studio</h2><p>Quick Brief → Gemini + Tavily live research → 5 Story Angles → Full Brief → Human QC → Scheduling.</p><a className="primary" href="/content-generator">Open Brief Studio</a></section>;
  return <><div className="metric-grid">{cards.map(c=><div className="metric" key={c[0]}><span>{c[0]}</span><strong>{c[1]}</strong><em>{c[2]}</em></div>)}</div><div className="grid-two"><section className="panel"><div className="panel-head"><div><h2>Performance Overview</h2><p>Views and reach trend</p></div><button className="ghost" onClick={()=>setActive("Content Performance")}>View details</button></div><div className="chart"><div className="bars">{[42,55,48,72,64,81,76,94,68,86,79,100].map((h,i)=><div key={i} className="bar" style={{height:h+"%"}}/>)}</div><div className="axis"><span>W1</span><span>W2</span><span>W3</span><span>W4</span></div></div></section><section className="panel"><div className="panel-head"><div><h2>Content Mix</h2><p>Contribution by format</p></div></div><div className="mix"><div className="donut"><div><b>1,240K</b><span>views</span></div></div><div className="legend"><div><i className="dot one"/>Reels <b>52%</b></div><div><i className="dot two"/>Carousels <b>31%</b></div><div><i className="dot three"/>Stories <b>17%</b></div></div></div></section></div><div className="grid-two"><section className="panel"><div className="panel-head"><div><h2>SMM Workflow</h2><p>Feature-parity production flow</p></div></div><div className="rows">{["Upload / Review Brand Intelligence","Quick Brief + Live Research","Full Brief + Human QC","Schedule + Design Workflow"].map((x,i)=><div className="row" key={x}><span className="rank">{i+1}</span><div><b>{x}</b><small>{["Brand context","5 Story Angles","AI Improve + editable sequence","Calendar + tasks"][i]}</small></div></div>)}</div></section><section className="panel"><div className="panel-head"><div><h2>Quick Actions</h2><p>Continue your social media workflow</p></div></div><div className="quick-grid"><button onClick={()=>setActive("Brand Intelligence")}><Brain/><span>Brand Intelligence</span></button><button onClick={()=>setActive("Brief Studio")}><Sparkles/><span>Brief Studio</span></button><button onClick={()=>setActive("Content Calendar")}><CalendarDays/><span>Content Calendar</span></button><button onClick={()=>setActive("Team Tasks")}><ListTodo/><span>Team Tasks</span></button></div></section></div></>;
 };
 return <main className="app-shell"><aside className={open?"sidebar open":"sidebar"}><div className="brand-row"><div className="brand-mark">P</div><div><b>Proxsis Strategy</b><span>Social Media Dashboard</span></div><button className="close-mobile" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="nav-label">WORKSPACE</div><nav>{sections.map(s=><button key={s.name} className={active===s.name?"nav-item active":"nav-item"} onClick={()=>{setActive(s.name);setOpen(false)}}>{s.icon}<span>{s.name}</span></button>)}</nav><div className="sidebar-bottom"><button className={active==="Users & Access"?"nav-item active":"nav-item"} onClick={()=>setActive("Users & Access")}><Settings size={18}/><span>Settings</span></button></div></aside><section className="content"><header className="topbar"><button className="mobile-menu" onClick={()=>setOpen(true)}><Menu size={20}/></button><div className="search"><Search size={17}/><input placeholder="Search dashboard..."/></div><div className="top-actions"><select value={activeBrand.id} onChange={e=>setActiveBrandId(e.target.value)}>{brands.map(brand=><option key={brand.id} value={brand.id}>{brand.name}</option>)}</select><button className="avatar">DS</button></div></header><div className="page"><div className="page-head"><div><p className="eyebrow">SOCIAL MEDIA OPERATING SYSTEM</p><h1>{active}</h1><p className="muted">Active brand: {activeBrand.name}. Analytics, content strategy, production, reporting, and team workflow in one workspace.</p></div><select className="period" value={period} onChange={e=>setPeriod(e.target.value)}><option>Last 30 Days</option><option>Last 7 Days</option><option>Last 90 Days</option></select></div>{render()}</div></section></main>;
}
