"use client";

import {createContext,useContext,useEffect,useMemo,useState} from "react";
import {loadBrands,loadUsers,type WorkspaceBrand} from "@/lib/workspace-store";
export type BrandOption={id:string;name:string};
export const BRAND_OPTIONS:BrandOption[]=[{id:"proxsis-consulting-group",name:"Proxsis Consulting Group"},{id:"proxsis-strategy",name:"Proxsis Strategy"},{id:"proxsis-infra",name:"Proxsis Infra"}];
const NO_ACCESS_BRAND:BrandOption={id:"__no_brand_access__",name:"No Brand Access"};
type ActiveBrandContextValue={activeBrand:BrandOption;brands:BrandOption[];setActiveBrandId:(id:string)=>void;refreshBrands:()=>void};
const ActiveBrandContext=createContext<ActiveBrandContextValue|null>(null);const ACTIVE_KEY="proxsis-workspace:active-brand:v1";
function sessionEmail(){if(typeof window==="undefined")return"";try{const raw=localStorage.getItem("proxsis-auth:session:v1");const session=raw?JSON.parse(raw):null;return String(session?.user?.email||"").toLowerCase()}catch{return""}}
export function ActiveBrandProvider({children}:{children:React.ReactNode}){const [brands,setBrands]=useState<BrandOption[]>(BRAND_OPTIONS);const [activeBrandId,setId]=useState(BRAND_OPTIONS[0].id);function refreshBrands(){const all=loadBrands().filter((b:WorkspaceBrand)=>b.status!=="inactive");const email=sessionEmail();const user=email?loadUsers().find(u=>u.email.toLowerCase()===email):null;const restricted=Boolean(user&&user.role!=="super_admin");const allowed=restricted?all.filter(b=>user!.brand_ids.includes(b.id)):all;const next=allowed.map(b=>({id:b.id,name:b.name}));const visible=restricted?(next.length?next:[NO_ACCESS_BRAND]):(next.length?next:BRAND_OPTIONS);setBrands(visible);setId(current=>(visible.some(b=>b.id===current)?current:visible[0].id))}useEffect(()=>{refreshBrands();try{const saved=localStorage.getItem(ACTIVE_KEY);if(saved)setId(saved)}catch{}const onUpdate=()=>refreshBrands();window.addEventListener("proxsis-workspace:updated",onUpdate as EventListener);window.addEventListener("storage",onUpdate);return()=>{window.removeEventListener("proxsis-workspace:updated",onUpdate as EventListener);window.removeEventListener("storage",onUpdate)}},[]);function setActiveBrandId(id:string){if(!brands.some(b=>b.id===id)||id===NO_ACCESS_BRAND.id)return;setId(id);try{localStorage.setItem(ACTIVE_KEY,id)}catch{}}const activeBrand=useMemo(()=>brands.find(b=>b.id===activeBrandId)||brands[0]||NO_ACCESS_BRAND,[brands,activeBrandId]);const value=useMemo(()=>({activeBrand,brands,setActiveBrandId,refreshBrands}),[activeBrand,brands]);return <ActiveBrandContext.Provider value={value}>{children}</ActiveBrandContext.Provider>}
export function useActiveBrand(){const context=useContext(ActiveBrandContext);if(!context)throw new Error("useActiveBrand must be used inside ActiveBrandProvider");return context}
