"use client";

import {createContext,useContext,useEffect,useMemo,useState} from "react";
import {loadBrands,type WorkspaceBrand} from "@/lib/workspace-store";
import {currentAccess} from "@/lib/access-control";
export type BrandOption={id:string;name:string};
export const BRAND_OPTIONS:BrandOption[]=[{id:"proxsis-consulting-group",name:"Proxsis Consulting Group"},{id:"proxsis-strategy",name:"Proxsis Strategy"},{id:"proxsis-infra",name:"Proxsis Infra"}];
const NO_ACCESS_BRAND:BrandOption={id:"__no_brand_access__",name:"No Brand Access"};
type ActiveBrandContextValue={activeBrand:BrandOption;brands:BrandOption[];setActiveBrandId:(id:string)=>void;refreshBrands:()=>void};
const ActiveBrandContext=createContext<ActiveBrandContextValue|null>(null);const ACTIVE_KEY="proxsis-workspace:active-brand:v1";
function normalizedName(value:string){return value.trim().toLowerCase().replace(/\s+/g," ")}
function mergedBrandCatalog(workspaceBrands:WorkspaceBrand[]):BrandOption[]{const byName=new Map<string,BrandOption>();for(const brand of BRAND_OPTIONS)byName.set(normalizedName(brand.name),brand);for(const brand of workspaceBrands){if(brand.status==="inactive")continue;byName.set(normalizedName(brand.name),{id:brand.id,name:brand.name})}return Array.from(byName.values()).sort((a,b)=>a.name.localeCompare(b.name))}
export function ActiveBrandProvider({children}:{children:React.ReactNode}){const [brands,setBrands]=useState<BrandOption[]>(BRAND_OPTIONS);const [activeBrandId,setId]=useState(BRAND_OPTIONS[0].id);function applyVisible(visible:BrandOption[]){setBrands(visible);setId(current=>visible.some(b=>b.id===current)?current:visible[0]?.id||NO_ACCESS_BRAND.id)}function refreshBrands(){const all=mergedBrandCatalog(loadBrands());applyVisible(all);void currentAccess().then(access=>{const restricted=access.foundationReady&&!access.allBrands;const allowed=restricted?all.filter(b=>access.brandIds.includes(b.id)):all;applyVisible(restricted?(allowed.length?allowed:[NO_ACCESS_BRAND]):all)})}useEffect(()=>{refreshBrands();try{const saved=localStorage.getItem(ACTIVE_KEY);if(saved)setId(saved)}catch{}const onUpdate=()=>refreshBrands();window.addEventListener("proxsis-workspace:updated",onUpdate as EventListener);window.addEventListener("storage",onUpdate);window.addEventListener("proxsis-auth:access-updated",onUpdate as EventListener);return()=>{window.removeEventListener("proxsis-workspace:updated",onUpdate as EventListener);window.removeEventListener("storage",onUpdate);window.removeEventListener("proxsis-auth:access-updated",onUpdate as EventListener)}},[]);function setActiveBrandId(id:string){if(!brands.some(b=>b.id===id)||id===NO_ACCESS_BRAND.id)return;setId(id);try{localStorage.setItem(ACTIVE_KEY,id)}catch{}}const activeBrand=useMemo(()=>brands.find(b=>b.id===activeBrandId)||brands[0]||NO_ACCESS_BRAND,[brands,activeBrandId]);const value=useMemo(()=>({activeBrand,brands,setActiveBrandId,refreshBrands}),[activeBrand,brands]);return <ActiveBrandContext.Provider value={value}>{children}</ActiveBrandContext.Provider>}
export function useActiveBrand(){const context=useContext(ActiveBrandContext);if(!context)throw new Error("useActiveBrand must be used inside ActiveBrandProvider");return context}
