"use client";

import {useEffect,useState} from "react";
import {usePathname} from "next/navigation";
import {loadBrief,loadCampaign} from "@/lib/smm-workflow";

type Result={overall_score:number;verdict:string;audience_fit:number;positioning_alignment:number;capability_relevance:number;market_relevance:number;claim_compliance:number;strengths:string[];misalignments:string[];recommendations:string[]};
export default function BrandAlignmentWidget(){const pathname=usePathname();const match=pathname.match(/^\/brief\/([^/]+)$/);const id=match?.[1]||"";const [open,setOpen]=useState(false);const [loading,setLoading]=useState(false);const [result,setResult]=useState<Result|null>(null);const [error,setError]=useState("");useEffect(()=>{setOpen(false);setResult(null);setError("")},[id]);if(!id)return null;async function run(){const brief=loadBrief(id);const bundle=brief?loadCampaign(brief.campaign_id):null;if(!brief||!bundle){setError("Brief atau Brand Intelligence tidak ditemukan.");setOpen(true);return}setOpen(true);setLoading(true);setError("");try{const res=await fetch("/api/ai/brand-alignment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brief,brandProfile:bundle.brand_profile})});const payload=await res.json().catch(()=>({}));if(!res.ok||!payload?.ok)throw new Error(payload?.error||"Brand Alignment QC gagal.");setResult(payload.data)}catch(err){setError(err instanceof Error?err.message:"Brand Alignment QC gagal.")}finally{setLoading(false)}}return <>{<button onClick={result?()=>setOpen(true):run} style={floating}>{result?`Brand Alignment ${Math.round(result.overall_score)}/100`:"Check Brand Alignment"}</button>}{open&&<div style={overlay}><section style={panel}><header style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start"}}><div><p style={eyebrow}>AI QUALITY CONTROL</p><h2 style={{margin:"4px 0"}}>Brand Alignment QC</h2><p style={muted}>Audience, positioning, capabilities, market relevance, dan claim compliance.</p></div><button onClick={()=>setOpen(false)} style={ghost}>Tutup</button></header>{loading&&<div style={note}>AI sedang membandingkan Full Brief dengan Brand Intelligence...</div>}{error&&<div style={errorBox}>{error}</div>}{result&&!loading&&<><div style={scoreBox}><div><small>OVERALL ALIGNMENT</small><strong>{Math.round(result.overall_score)}<span>/100</span></strong></div><b>{result.verdict}</b></div><div style={grid}>{[["Audience Fit",result.audience_fit],["Positioning",result.positioning_alignment],["Capabilities",result.capability_relevance],["Market",result.market_relevance],["Claim Compliance",result.claim_compliance]].map(([label,value])=><div key={String(label)} style={metric}><span>{label}</span><strong>{Math.round(Number(value))}</strong></div>)}</div><Section title="Yang sudah align" items={result.strengths} tone="#eef8f1"/><Section title="Potential misalignment" items={result.misalignments} tone="#fff8e9"/><Section title="Recommended action" items={result.recommendations} tone="#f6f3f4"/><button onClick={run} style={{...ghost,width:"100%",justifyContent:"center",marginTop:12}}>Run Check Again</button></>}</section></div>}</>}
function Section({title,items,tone}:{title:string;items:string[];tone:string}){return <div style={{background:tone,borderRadius:12,padding:13,marginTop:10}}><strong style={{fontSize:12}}>{title}</strong>{items?.length?<div style={{fontSize:11,lineHeight:1.6,marginTop:6}}>{items.map((x,i)=><div key={i}>• {x}</div>)}</div>:<p style={{fontSize:11,color:"#756b70"}}>Tidak ada catatan material.</p>}</div>}
const floating:React.CSSProperties={position:"fixed",right:20,bottom:20,zIndex:55,border:0,borderRadius:12,padding:"11px 15px",background:"#2a2426",color:"white",fontWeight:800,cursor:"pointer",boxShadow:"0 10px 28px rgba(30,20,24,.2)"};const overlay:React.CSSProperties={position:"fixed",inset:0,zIndex:70,background:"rgba(35,27,30,.45)",display:"flex",justifyContent:"flex-end",alignItems:"stretch",padding:14};const panel:React.CSSProperties={width:"min(520px,100%)",height:"100%",overflow:"auto",background:"white",borderRadius:20,padding:22,boxShadow:"0 18px 50px rgba(30,20,24,.25)"};const eyebrow:React.CSSProperties={fontSize:10,fontWeight:800,letterSpacing:".13em",color:"#98142f",margin:0};const muted:React.CSSProperties={fontSize:12,color:"#756b70",lineHeight:1.5,maxWidth:360};const ghost:React.CSSProperties={display:"inline-flex",border:"1px solid #ddd5d8",background:"white",borderRadius:9,padding:"8px 10px",fontWeight:700,cursor:"pointer"};const note:React.CSSProperties={marginTop:16,padding:13,borderRadius:10,background:"#eef4ff",color:"#355b8a",fontSize:12};const errorBox:React.CSSProperties={marginTop:16,padding:13,borderRadius:10,background:"#fff0f1",color:"#a3152d",fontSize:12};const scoreBox:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"end",gap:14,background:"#2a2426",color:"white",borderRadius:14,padding:16,marginTop:16};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8,marginTop:10};const metric:React.CSSProperties={border:"1px solid #eee8ea",borderRadius:10,padding:11,display:"flex",justifyContent:"space-between",fontSize:11};
