"use client";

import {useEffect,useMemo,useState} from "react";
import {readSession} from "@/lib/access-control";
import {hydrateSharedTasks,loadTasks,type WorkspaceTask} from "@/lib/workspace-store";

type TeamMember={id:string;user_id:string;display_name:string;role:string;email:string;active:boolean};
const statusLabel:Record<WorkspaceTask["status"],string>={todo:"To-do",in_progress:"In Progress",review:"Review",done:"Completed"};
function authHeaders():Record<string,string>{const token=String(readSession()?.access_token||"");return token?{Authorization:`Bearer ${token}`}:{} }

export default function OverviewTaskForce(){
 const[tasks,setTasks]=useState<WorkspaceTask[]>([]);const[member,setMember]=useState<TeamMember|null>(null);const[error,setError]=useState("");
 const currentEmail=String(readSession()?.user?.email||"").trim().toLowerCase();
 useEffect(()=>{let active=true;const refresh=()=>{if(active)setTasks(loadTasks())};async function load(){try{const [rows,response]=await Promise.all([hydrateSharedTasks(),fetch("/api/team-members",{headers:authHeaders(),cache:"no-store"})]);if(active)setTasks(rows);const payload=await response.json().catch(()=>({}));if(!response.ok||!payload?.ok)throw new Error(payload?.error||"Gagal memuat member tim.");const found=((payload.members||[]) as TeamMember[]).find(item=>String(item.email||"").trim().toLowerCase()===currentEmail)||null;if(active)setMember(found)}catch(err){if(active)setError(err instanceof Error?err.message:"Gagal memuat task force.")}}void load();window.addEventListener("proxsis-workspace:updated",refresh as EventListener);window.addEventListener("focus",refresh);return()=>{active=false;window.removeEventListener("proxsis-workspace:updated",refresh as EventListener);window.removeEventListener("focus",refresh)}},[currentEmail]);
 const mine=useMemo(()=>tasks.filter(task=>String(task.assignee||"").trim().toLowerCase()===currentEmail),[tasks,currentEmail]);const activeTasks=useMemo(()=>mine.filter(task=>task.status!=="done"),[mine]);const counts=useMemo(()=>({todo:mine.filter(t=>t.status==="todo").length,in_progress:mine.filter(t=>t.status==="in_progress").length,review:mine.filter(t=>t.status==="review").length,done:mine.filter(t=>t.status==="done").length}),[mine]);
 if(!currentEmail)return null;
 return <section className="panel" style={{marginBottom:18,padding:18}}><div className="panel-head"><div><p className="eyebrow" style={{margin:0}}>MY TASK FORCE</p><h2 style={{margin:"5px 0 0"}}>Pekerjaan {member?.display_name||currentEmail}</h2><p style={{margin:"5px 0 0",fontSize:11,color:"#8a8185"}}>Role: {member?.role?.replaceAll("_"," ")||"member"} · hanya task akun yang sedang login</p></div><a className="ghost" href="/tasks" style={{textDecoration:"none"}}>Buka Semua Task →</a></div>{error&&<div style={{marginTop:12,padding:10,borderRadius:9,background:"#fff0f1",color:"#a3152d",fontSize:11}}>{error}</div>}{activeTasks.length>0&&<a href="/tasks" style={{display:"block",marginTop:14,padding:14,border:"1px solid #ead4d9",borderRadius:12,background:"#fbf3f5",color:"inherit",textDecoration:"none"}}><b style={{fontSize:12,color:"#8d1730"}}>Assignment masuk · {activeTasks.length} tugas aktif</b><div style={{display:"grid",gap:4,marginTop:7}}>{activeTasks.slice(0,3).map(task=><span key={task.id} style={{fontSize:11,color:"#665b5f"}}>• {task.title} · {statusLabel[task.status]}</span>)}{activeTasks.length>3&&<span style={{fontSize:11,fontWeight:700,color:"#8d1730"}}>+ {activeTasks.length-3} assignment lainnya</span>}</div></a>}<div style={{display:"grid",gridTemplateColumns:"1.3fr repeat(4,minmax(0,1fr))",gap:9,marginTop:14}}><a href="/tasks" style={metricLink}><small style={metricLabel}>My Tasks</small><strong style={metricValue}>{activeTasks.length}</strong><span style={metricNote}>masih harus diselesaikan</span></a>{(["todo","in_progress","review","done"] as const).map(status=><a href="/tasks" key={status} style={metricLink}><small style={metricLabel}>{statusLabel[status]}</small><strong style={metricValue}>{counts[status]}</strong><span style={metricNote}>{status==="todo"?"Belum dimulai":status==="in_progress"?"Sedang dikerjakan":status==="review"?"Menunggu review":"Sudah selesai"}</span></a>)}</div></section>
}

const metricLink:React.CSSProperties={display:"block",border:"1px solid #ebe4e6",borderRadius:11,padding:13,background:"#fff",textDecoration:"none",color:"inherit"};const metricLabel:React.CSSProperties={fontSize:9,fontWeight:800,textTransform:"uppercase",letterSpacing:".08em",color:"#8d1730"};const metricValue:React.CSSProperties={display:"block",fontSize:26,lineHeight:1.1,marginTop:6};const metricNote:React.CSSProperties={display:"block",fontSize:10,color:"#80757a",marginTop:4};
