"use client";

import {useEffect,useMemo,useState} from "react";
import {usePathname} from "next/navigation";
import {loadBrief} from "@/lib/smm-workflow";
import {loadTasks,loadUsers,upsertTask,type WorkspaceTask} from "@/lib/workspace-store";

export default function TaskAssignmentWidget(){const pathname=usePathname();const match=pathname.match(/^\/brief\/([^/]+)(?:\/expansion\/(linkedin|seo_geo))?$/);const briefId=match?.[1]||"";const channel=(match?.[2]||"social") as "social"|"linkedin"|"seo_geo";const brief=useMemo(()=>briefId?loadBrief(briefId):null,[briefId]);const users=useMemo(()=>loadUsers(),[briefId]);const [open,setOpen]=useState(false);const [assignee,setAssignee]=useState("");const [due,setDue]=useState("");const [priority,setPriority]=useState<WorkspaceTask["priority"]>("medium");const [message,setMessage]=useState("");const existing=useMemo(()=>loadTasks().find(t=>t.brief_id===briefId&&t.channel===channel)||null,[briefId,channel,open]);useEffect(()=>{setAssignee(existing?.assignee||"");setDue(existing?.due_date||"");setPriority(existing?.priority||"medium")},[existing]);if(!briefId||!brief)return null;function save(){const now=new Date().toISOString();const task:WorkspaceTask={id:existing?.id||crypto.randomUUID(),brand_id:brief.brand_id||"",title:existing?.title||`${channel==="social"?"Social":channel==="linkedin"?"LinkedIn":"SEO/GEO"}: ${brief.working_title}`,description:existing?.description||"Production task generated from content workflow.",brief_id:briefId,channel,assignee:assignee||undefined,due_date:due||undefined,status:existing?.status||"todo",priority,created_at:existing?.created_at||now,updated_at:now};upsertTask(task);setMessage("Task assignment tersimpan.");setTimeout(()=>setOpen(false),700)}return <>{<button onClick={()=>setOpen(true)} style={float}>Assign Task</button>}{open&&<div style={overlay}><section style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:12}}><div><p style={eyebrow}>PRODUCTION TASK</p><h2 style={{margin:"4px 0"}}>{existing?"Update Assignment":"Assign Content"}</h2><p style={muted}>{channel.toUpperCase()} · {brief.working_title}</p></div><button style={ghost} onClick={()=>setOpen(false)}>✕</button></div>{message&&<div style={success}>{message}</div>}<label style={label}>Assignee<select style={input} value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Unassigned</option>{users.map(u=><option key={u.id} value={u.email}>{u.name} · {u.role.replaceAll("_"," ")}</option>)}</select></label><label style={label}>Due Date<input style={input} type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label style={label}>Priority<select style={input} value={priority} onChange={e=>setPriority(e.target.value as WorkspaceTask["priority"])}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><button style={{...primary,width:"100%",marginTop:16}} onClick={save}>Save Assignment</button><a href="/tasks" style={link}>Open Team Tasks →</a></section></div>}</>}
const float:React.CSSProperties={position:"fixed",right:20,bottom:72,zIndex:54,border:"1px solid #d8cdd1",borderRadius:12,padding:"10px 14px",background:"white",color:"#6d303e",fontWeight:800,cursor:"pointer",boxShadow:"0 8px 24px rgba(30,20,24,.12)"};const overlay:React.CSSProperties={position:"fixed",inset:0,zIndex:75,background:"rgba(35,27,30,.45)",display:"grid",placeItems:"center",padding:16};const card:React.CSSProperties={width:"min(480px,100%)",background:"white",borderRadius:18,padding:20,boxShadow:"0 18px 50px rgba(30,20,24,.25)"};const eyebrow:React.CSSProperties={fontSize:10,fontWeight:800,letterSpacing:".13em",color:"#98142f",margin:0};const muted:React.CSSProperties={fontSize:12,color:"#756b70",lineHeight:1.5,maxWidth:350};const ghost:React.CSSProperties={border:"1px solid #ddd5d8",background:"white",borderRadius:9,padding:"8px 10px",fontWeight:700,cursor:"pointer"};const label:React.CSSProperties={display:"grid",gap:6,fontSize:11,fontWeight:700,marginTop:13};const input:React.CSSProperties={border:"1px solid #ddd5d8",borderRadius:9,padding:"10px 11px",background:"white"};const primary:React.CSSProperties={border:0,borderRadius:9,padding:"10px 13px",background:"#98142f",color:"white",fontWeight:800,cursor:"pointer"};const success:React.CSSProperties={marginTop:10,padding:10,borderRadius:9,background:"#eef8f1",color:"#267347",fontSize:12};const link:React.CSSProperties={display:"block",marginTop:10,textAlign:"center",fontSize:11,color:"#6d303e",fontWeight:700,textDecoration:"none"};
