"use client";
import {useEffect} from "react";
import {BRAND_OPTIONS,useActiveBrand} from "@/components/active-brand";
import {hydrateAllBriefsFromSupabase,hydrateAllCampaignsFromSupabase,reconcileLegacyBrandIdentity} from "@/lib/smm-workflow";
import {hydrateAllExpansionCalendarFromSupabase} from "@/lib/expansion-calendar";
import {fetchWorkspaceRows,hydrateSharedTasks,hydrateWorkspaceSettings,supabaseConfigured,type ExpansionMeta,type WorkspaceBrand,type WorkspaceUser} from "@/lib/workspace-store";
type ExpansionRow={brief_id:string;channel:"linkedin"|"seo_geo";content:Record<string,unknown>};
function normalizedName(value:string){return value.trim().toLowerCase().replace(/\s+/g," ")}
function mergeBrands(remote:WorkspaceBrand[]){let local:WorkspaceBrand[]=[];try{const raw=localStorage.getItem("proxsis-workspace:brands:v1");const parsed=raw?JSON.parse(raw):[];if(Array.isArray(parsed))local=parsed}catch{}const byName=new Map<string,WorkspaceBrand>();for(const brand of BRAND_OPTIONS)byName.set(normalizedName(brand.name),{...brand,status:"active"});for(const brand of local)if(brand?.id&&brand?.name)byName.set(normalizedName(brand.name),brand);for(const brand of remote)if(brand?.id&&brand?.name)byName.set(normalizedName(brand.name),brand);return Array.from(byName.values()).sort((a,b)=>a.name.localeCompare(b.name))}
export default function WorkspaceHydrator(){const {activeBrand,refreshBrands}=useActiveBrand();useEffect(()=>{if(!supabaseConfigured())return;let cancelled=false;async function run(){await reconcileLegacyBrandIdentity(activeBrand.id,activeBrand.name);await Promise.all([hydrateAllCampaignsFromSupabase(),hydrateAllBriefsFromSupabase(),hydrateAllExpansionCalendarFromSupabase(),hydrateWorkspaceSettings()]);const [brands,users,,metas,expansions]=await Promise.all([fetchWorkspaceRows<WorkspaceBrand>("brands","select=*&order=name.asc"),fetchWorkspaceRows<WorkspaceUser>("workspace_users","select=*&order=name.asc"),hydrateSharedTasks(),fetchWorkspaceRows<ExpansionMeta>("content_expansion_meta","select=*&order=updated_at.desc&limit=1000"),fetchWorkspaceRows<ExpansionRow>("content_expansions","select=brief_id,channel,content")]);if(cancelled)return;try{localStorage.setItem("proxsis-workspace:brands:v1",JSON.stringify(mergeBrands(brands)));if(users.length)localStorage.setItem("proxsis-workspace:users:v1",JSON.stringify(users));if(metas.length){const map:Record<string,ExpansionMeta>={};for(const meta of metas)map[`${meta.brief_id}:${meta.channel}`]=meta;localStorage.setItem("proxsis-workspace:expansion-meta:v1",JSON.stringify(map))}for(const row of expansions)if(row?.brief_id&&row?.channel&&row?.content)localStorage.setItem(`proxsis-smm:expansion:${row.brief_id}:${row.channel}`,JSON.stringify(row.content));window.dispatchEvent(new Event("proxsis-workspace:updated"));refreshBrands()}catch{}}void run();return()=>{cancelled=true}},[activeBrand.id,activeBrand.name]);return null}