export type PermissionKey=
  |"overview.view"|"brief.view"|"brief.create"|"brief.ai_generate"|"brief.edit"|"brief.improve"|"brief.qc"
  |"calendar.view"|"calendar.schedule"|"calendar.reschedule"|"design.view"|"design.update_status"|"design.update_link"
  |"brand.view"|"brand.edit"|"brand.upload"|"brand.create"|"brand.delete"|"analytics.view"|"analytics.export"
  |"users.view"|"users.invite"|"users.manage"|"settings.manage";

export const PERMISSION_KEYS:PermissionKey[]=["overview.view","brief.view","brief.create","brief.ai_generate","brief.edit","brief.improve","brief.qc","calendar.view","calendar.schedule","calendar.reschedule","design.view","design.update_status","design.update_link","brand.view","brand.edit","brand.upload","brand.create","brand.delete","analytics.view","analytics.export","users.view","users.invite","users.manage","settings.manage"];

export type AccessSnapshot={foundationReady:boolean;roleKey:string|null;roleName:string|null;permissions:PermissionKey[];brandIds:string[];allBrands:boolean;userId:string};
const SESSION_KEY="proxsis-auth:session:v1";
function config(){return{url:process.env.NEXT_PUBLIC_SUPABASE_URL||"",key:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||""}}
export function readSession(){if(typeof window==="undefined")return null;try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw):null}catch{return null}}
function headers(){const {key}=config();const session=readSession();return{apikey:key,Authorization:`Bearer ${session?.access_token||key}`,"Content-Type":"application/json"}}
export async function rpc<T=unknown>(name:string,body:Record<string,unknown>={}){const {url,key}=config();if(!url||!key)throw new Error("Supabase belum dikonfigurasi.");const res=await fetch(`${url}/rest/v1/rpc/${name}`,{method:"POST",headers:headers(),body:JSON.stringify(body),cache:"no-store"});const payload=await res.json().catch(()=>null);if(!res.ok)throw new Error((payload as any)?.message||(payload as any)?.error||`RPC ${name} gagal.`);return payload as T}
export async function hasPermission(permission:PermissionKey){const {url,key}=config();if(!url||!key)return true;try{return Boolean(await rpc<boolean>("smm_has_access_permission",{p_permission_key:permission}))}catch{return true}}
export async function currentAccess():Promise<AccessSnapshot>{const session=readSession();if(!session?.user?.id)return{foundationReady:false,roleKey:null,roleName:null,permissions:[...PERMISSION_KEYS],brandIds:[],allBrands:true,userId:"local"};const userId=String(session.user.id);try{const {url}=config();const h=headers();const roleRes=await fetch(`${url}/rest/v1/user_roles?select=role_id,roles(key,name)&user_id=eq.${encodeURIComponent(userId)}`,{headers:h,cache:"no-store"});if(!roleRes.ok)throw new Error("foundation unavailable");const roleRows=await roleRes.json();const role=roleRows?.[0]?.roles||null;const roleId=roleRows?.[0]?.role_id||"";const [catalogRes,baseRes,overrideRes,brandRes]=await Promise.all([
 fetch(`${url}/rest/v1/permissions?select=id,key`,{headers:h,cache:"no-store"}),
 roleId?fetch(`${url}/rest/v1/role_permissions?select=permission_id,allowed&role_id=eq.${encodeURIComponent(roleId)}`,{headers:h,cache:"no-store"}):Promise.resolve(null),
 fetch(`${url}/rest/v1/user_permission_overrides?select=permission_id,allowed&user_id=eq.${encodeURIComponent(userId)}`,{headers:h,cache:"no-store"}),
 fetch(`${url}/rest/v1/user_brand_access?select=brand_id&user_id=eq.${encodeURIComponent(userId)}`,{headers:h,cache:"no-store"})]);
 const catalog=(await catalogRes.json()) as Array<{id:string;key:string}>;const keyById=new Map(catalog.filter(x=>PERMISSION_KEYS.includes(x.key as PermissionKey)).map(x=>[String(x.id),x.key as PermissionKey]));const allowed=new Set<PermissionKey>();if(baseRes){for(const row of await baseRes.json())if(row.allowed&&keyById.has(String(row.permission_id)))allowed.add(keyById.get(String(row.permission_id))!)}for(const row of await overrideRes.json()){const k=keyById.get(String(row.permission_id));if(!k)continue;if(row.allowed)allowed.add(k);else allowed.delete(k)}const brandIds=(await brandRes.json()).map((x:any)=>String(x.brand_id));if(role?.key==="super_admin")for(const k of PERMISSION_KEYS)allowed.add(k);return{foundationReady:true,roleKey:role?.key||null,roleName:role?.name||null,permissions:[...allowed],brandIds,allBrands:role?.key==="super_admin",userId};}catch{return{foundationReady:false,roleKey:null,roleName:null,permissions:[...PERMISSION_KEYS],brandIds:[],allBrands:true,userId}}}
