export type WorkspaceBrand={id:string;name:string;website?:string;status?:"active"|"inactive";created_at?:string};
export type WorkspaceRole="super_admin"|"manager"|"content_writer"|"designer"|"viewer";
export type WorkspaceUser={id:string;name:string;email:string;role:WorkspaceRole;brand_ids:string[];permissions:string[];status:"active"|"inactive"};
export type WorkspaceTask={id:string;brand_id:string;title:string;description?:string;brief_id?:string;channel?:"social"|"linkedin"|"seo_geo";assignee?:string;due_date?:string;status:"todo"|"in_progress"|"review"|"done";priority:"low"|"medium"|"high";created_at:string;updated_at:string};
export type ExpansionMeta={brief_id:string;channel:"linkedin"|"seo_geo";scheduled_for?:string;human_qc:"pending"|"approved";human_qc_at?:string;alignment?:{overall:number;core_message:number;audience:number;brand_pov:number;facts_claims:number;channel_fit:number;verdict:string;risks:string[];recommendations:string[]};master_updated_at?:string;updated_at:string};
export type WorkspaceSettings={id:"default";timezone:string;default_objective:string;default_cta:string;default_format:"auto"|"carousel"|"reels"|"single_post";story_qc_threshold:number;brand_alignment_threshold:number;derivative_alignment_threshold:number;calendar_default_scope:"active_brand"|"all_brands";auto_ready_to_design:boolean;updated_at:string};
const KEYS={brands:"proxsis-workspace:brands:v1",users:"proxsis-workspace:users:v1",tasks:"proxsis-workspace:tasks:v1",expansionMeta:"proxsis-workspace:expansion-meta:v1",settings:"proxsis-workspace:settings:v1"};
const DEFAULT_BRANDS:WorkspaceBrand[]=[{id:"proxsis-consulting-group",name:"Proxsis Consulting Group",status:"active"},{id:"proxsis-strategy",name:"Proxsis Strategy",status:"active"},{id:"proxsis-infra",name:"Proxsis Infra",status:"active"}];
const DEFAULT_USERS:WorkspaceUser[]=[{id:"local-admin",name:"Workspace Admin",email:"admin@local",role:"super_admin",brand_ids:[],permissions:["*"],status:"active"}];
export const DEFAULT_SETTINGS:WorkspaceSettings={id:"default",timezone:"Asia/Jakarta",default_objective:"awareness + consideration",default_cta:"Pelajari lebih lanjut",default_format:"auto",story_qc_threshold:90,brand_alignment_threshold:85,derivative_alignment_threshold:85,calendar_default_scope:"active_brand",auto_ready_to_design:true,updated_at:new Date(0).toISOString()};
function read<T>(key:string,fallback:T):T{if(typeof window==="undefined")return fallback;try{const raw=window.localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function write<T>(key:string,value:T){if(typeof window==="undefined")return;window.localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new CustomEvent("proxsis-workspace:updated",{detail:{key}}))}
export function supabaseConfigured(){return Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)}
function remoteHeaders(){const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"";let token=key;if(typeof window!=="undefined"){try{const raw=localStorage.getItem("proxsis-auth:session:v1");const session=raw?JSON.parse(raw):null;if(session?.access_token)token=session.access_token}catch{}}return{apikey:key,Authorization:`Bearer ${token}`,"Content-Type":"application/json"}}
function taskApiHeaders(){if(typeof window==="undefined")return{"Content-Type":"application/json"};try{const raw=localStorage.getItem("proxsis-auth:session:v1");const session=raw?JSON.parse(raw):null;return{"Content-Type":"application/json",...(session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{})}}catch{return{"Content-Type":"application/json"}}}
export async function syncWorkspaceRecord(table:string,payload:unknown,onConflict="id"){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;if(!url||!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)return false;try{const response=await fetch(`${url}/rest/v1/${table}?on_conflict=${encodeURIComponent(onConflict)}`,{method:"POST",headers:{...remoteHeaders(),Prefer:"resolution=merge-duplicates"},body:JSON.stringify(payload)});return response.ok}catch{return false}}
export async function fetchWorkspaceRows<T>(table:string,query="select=*"):Promise<T[]>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL;if(!url||!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)return[];try{const response=await fetch(`${url}/rest/v1/${table}?${query}`,{headers:remoteHeaders(),cache:"no-store"});if(!response.ok)return[];const rows=await response.json();return Array.isArray(rows)?rows:[]}catch{return[]}}
export function loadBrands(){return read<WorkspaceBrand[]>(KEYS.brands,DEFAULT_BRANDS)}
// Brand catalog can include legacy slug IDs that are not valid UUIDs for the shared SMM `brands` table.
// Therefore catalog edits stay local here; shared/core brand writes are handled explicitly by the Brands workspace.
export function saveBrands(items:WorkspaceBrand[]){write(KEYS.brands,items)}
export function upsertBrand(item:WorkspaceBrand){const all=loadBrands();const next=[item,...all.filter(x=>x.id!==item.id)];saveBrands(next);return next}
export function removeBrand(id:string){const next=loadBrands().filter(x=>x.id!==id);saveBrands(next);return next}
export function loadUsers(){return read<WorkspaceUser[]>(KEYS.users,DEFAULT_USERS)}
export function saveUsers(items:WorkspaceUser[]){write(KEYS.users,items);void syncWorkspaceRecord("workspace_users",items)}
export function upsertUser(item:WorkspaceUser){const next=[item,...loadUsers().filter(x=>x.id!==item.id)];saveUsers(next);return next}
export function loadTasks(){return read<WorkspaceTask[]>(KEYS.tasks,[])}
export async function hydrateSharedTasks(){if(typeof window==="undefined")return[];try{const response=await fetch("/api/tasks",{headers:taskApiHeaders(),cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload?.ok)return loadTasks();const tasks=Array.isArray(payload.tasks)?payload.tasks as WorkspaceTask[]:[];write(KEYS.tasks,tasks);return tasks}catch{return loadTasks()}}
export function saveTasks(items:WorkspaceTask[]){write(KEYS.tasks,items)}
export function upsertTask(item:WorkspaceTask){const next=[item,...loadTasks().filter(x=>x.id!==item.id)];write(KEYS.tasks,next);if(typeof window!=="undefined")void fetch("/api/tasks",{method:"POST",headers:taskApiHeaders(),body:JSON.stringify(item)}).then(async response=>{if(!response.ok)return;await hydrateSharedTasks()}).catch(()=>{});return next}
export function removeTask(id:string){const next=loadTasks().filter(x=>x.id!==id);write(KEYS.tasks,next);if(typeof window!=="undefined")void fetch(`/api/tasks?id=${encodeURIComponent(id)}`,{method:"DELETE",headers:taskApiHeaders()}).then(async response=>{if(!response.ok)return;await hydrateSharedTasks()}).catch(()=>{});return next}
export function expansionMetaKey(briefId:string,channel:"linkedin"|"seo_geo"){return `${briefId}:${channel}`}
export function loadExpansionMeta(){return read<Record<string,ExpansionMeta>>(KEYS.expansionMeta,{})}
export function getExpansionMeta(briefId:string,channel:"linkedin"|"seo_geo"){return loadExpansionMeta()[expansionMetaKey(briefId,channel)]||null}
export function saveExpansionMeta(meta:ExpansionMeta){const all=loadExpansionMeta();all[expansionMetaKey(meta.brief_id,meta.channel)]=meta;write(KEYS.expansionMeta,all);void syncWorkspaceRecord("content_expansion_meta",meta,"brief_id,channel");if(typeof window!=="undefined"){try{const raw=localStorage.getItem(`proxsis-smm:expansion:${meta.brief_id}:${meta.channel}`);if(raw)void syncWorkspaceRecord("content_expansions",{brief_id:meta.brief_id,channel:meta.channel,brand_id:null,content:JSON.parse(raw),master_updated_at:meta.master_updated_at||null,updated_at:meta.updated_at},"brief_id,channel")}catch{}}return meta}
export function loadWorkspaceSettings(){return read<WorkspaceSettings>(KEYS.settings,DEFAULT_SETTINGS)}
export function saveWorkspaceSettings(settings:WorkspaceSettings){write(KEYS.settings,settings);void syncWorkspaceRecord("workspace_settings",settings);return settings}
export async function hydrateWorkspaceSettings(){const rows=await fetchWorkspaceRows<WorkspaceSettings>("workspace_settings","select=*&id=eq.default&limit=1");if(rows[0]){write(KEYS.settings,rows[0]);return rows[0]}return loadWorkspaceSettings()}
export const ROLE_PRESETS:Record<WorkspaceRole,string[]>={super_admin:["*"],manager:["brief.read","brief.write","calendar.manage","tasks.manage","brand.read","analytics.read","reports.read"],content_writer:["brief.read","brief.write","expansion.write","calendar.read","tasks.read","brand.read"],designer:["brief.read","calendar.read","design.manage","tasks.write","brand.read"],viewer:["brief.read","calendar.read","tasks.read","brand.read","analytics.read","reports.read"]};