import { average, clampScore, compactJson, createStructuredJson } from "@/lib/ai/core";
import { briefSchema, qualitySchema } from "@/lib/ai/schemas";

export type BriefOutput = {
  content_objective:string;target_audience:string;funnel_stage:"awareness"|"consideration"|"conversion";editorial_thesis:string;case_evidence:string;why_this_case:string;tension:string;core_insight:string;brand_pov:string;capability_bridge:string;story_arc:string;cta:string;fact_check_notes:string;
  sections:Array<{sequence_no:number;section_type:"slide"|"scene";purpose:string;headline:string;supporting_copy:string;evidence_needed:string;visual_direction:string;transition_to_next:string}>;
};
export type QualityReview={case_strength:number;hook_strength:number;tension:number;insight_depth:number;mechanism_clarity:number;audience_relevance:number;brand_fit:number;brand_pov:number;story_flow:number;non_generic_score:number;conversion_naturalness:number;evidence_safety:number;reviewer_notes:string;required_revisions:string[]};
const qualityKeys:Array<keyof Omit<QualityReview,"reviewer_notes"|"required_revisions">>=["case_strength","hook_strength","tension","insight_depth","mechanism_clarity","audience_relevance","brand_fit","brand_pov","story_flow","non_generic_score","conversion_naturalness","evidence_safety"];
export function reviewTotal(review:QualityReview){return average(qualityKeys.map(key=>clampScore(Number(review[key]))))*10}

export async function generateBrief({knowledge,context,sourceList,format,revisionNotes,currentBrief,userNotes}:{knowledge:string;context:unknown;sourceList:string;format:"carousel"|"reels"|"single_post";revisionNotes?:string[];currentBrief?:BriefOutput;userNotes?:string}){
  const formatInstruction=format==="reels"?"Buat 7-10 scene untuk Reels 45-90 detik. section_type=scene.":format==="single_post"?"Buat 1-3 section untuk single post. section_type=slide untuk kompatibilitas.":"Buat 8-9 slide carousel. section_type=slide.";
  const revisionBlock=revisionNotes?.length?`\nMANDATORY EDITOR REVISIONS:\n- ${revisionNotes.join("\n- ")}`:"";
  const currentBlock=currentBrief?`\nCURRENT BRIEF TO IMPROVE:\n${compactJson(currentBrief)}`:"";
  const userBlock=userNotes?.trim()?`\nCATATAN MANUSIA YANG WAJIB DIPERTIMBANGKAN:\n${userNotes.trim()}`:"";
  return createStructuredJson<BriefOutput>({schema:briefSchema as unknown as Record<string,unknown>,system:"Kamu adalah elite B2B case-study storyteller, senior content strategist, dan senior copywriter/editorial director. Semua output human-facing wajib Bahasa Indonesia. Tulis brief eksekutif evidence-led, case-first, high-retention, dan tidak terasa seperti template AI.",user:`EDITORIAL KNOWLEDGE BASE:\n${knowledge}\n\nCONTEXT:\n${compactJson(context)}\n\nVERIFICATION SOURCES:\n${sourceList}\n\nTASK:\n${currentBrief?"Perbaiki brief yang ada secara targeted.":"Buat full storytelling brief."}\n${formatInstruction}\n\nWAJIB: curiosity gap legitimate; hook spesifik pada kasus; satu pekerjaan utama per slide/scene; open loop harus dibayar dengan reveal; headline harus kuat tanpa supporting copy; brand/CTA muncul setelah value; gunakan specificity, contradiction, decision tension, business stakes jika didukung evidence.\n\nCASE-FIRST RULE: bila verified case kuat tersedia, buka dari kasus nyata, lanjut Context → Tension → Turning Point → Mechanism → Outcome → Executive Insight → Brand POV → Capability Bridge/CTA. Mechanism adalah jantung konten.\n\nQUALITY: semua fakta hanya dari evidence; gunakan [S1]/[S2] bila relevan; jangan mengarang angka/quote/motif/legal finding/causal claim; supporting copy harus executable; visual direction konkret; hindari AI slop dan listicle dangkal.${revisionBlock}${currentBlock}${userBlock}`,temperature:currentBrief?0.28:0.35});
}

export async function reviewBrief({knowledge,context,brief}:{knowledge:string;context:unknown;brief:BriefOutput}){
  return createStructuredJson<QualityReview>({schema:qualitySchema as unknown as Record<string,unknown>,system:"Kamu adalah executive editorial director sekaligus senior copywriter yang keras. Tolak konten generik, unsupported, dan copy yang hanya terdengar pintar.",user:`EDITORIAL STANDARD:\n${knowledge}\n\nCONTEXT + SOURCES:\n${compactJson(context)}\n\nBRIEF:\n${compactJson(brief)}\n\nSkor 0-10 secara ketat untuk seluruh dimensi schema. Skor 9+ berarti publish-worthy setelah human fact check. Penalti besar untuk opening generik, clickbait, mekanisme lemah, payoff tidak memenuhi promise, brand selling terlalu cepat, insight tanpa riset, slide repetitif, visual abstrak, filler/jargon/AI slop. required_revisions harus konkret per bagian/slide.`,temperature:0.15});
}
