"use client";

import {FormEvent,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";

const SESSION_KEY="proxsis-auth:session:v1";
export default function LoginPage(){
 const router=useRouter();const params=useSearchParams();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 const configured=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");try{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new Error("Supabase Auth belum dikonfigurasi. Dashboard tetap dapat digunakan dalam local mode.");const res=await fetch(`${url}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:key,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const payload=await res.json().catch(()=>({}));if(!res.ok||!payload?.access_token)throw new Error(payload?.error_description||payload?.msg||payload?.error||`Login gagal (HTTP ${res.status}).`);localStorage.setItem(SESSION_KEY,JSON.stringify({...payload,expires_at:Math.floor(Date.now()/1000)+Number(payload.expires_in||3600)}));router.replace(params.get("next")||"/")}catch(err){setError(err instanceof Error?err.message:"Login gagal.")}finally{setLoading(false)}}
 return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:24,background:"#f8f5f6",fontFamily:"Arial,sans-serif",color:"#251f21"}}><form onSubmit={submit} style={{width:"100%",maxWidth:420,background:"white",border:"1px solid #e7dfe2",borderRadius:22,padding:28,boxShadow:"0 18px 50px rgba(60,30,40,.08)"}}><div style={{width:42,height:42,borderRadius:12,display:"grid",placeItems:"center",background:"#98142f",color:"white",fontWeight:900}}>P</div><p style={{fontSize:11,fontWeight:800,letterSpacing:".14em",color:"#98142f",margin:"18px 0 5px"}}>PROXSIS STRATEGY</p><h1 style={{margin:0,fontSize:28}}>Workspace Login</h1><p style={{color:"#756b70",fontSize:13,lineHeight:1.6}}>Masuk menggunakan akun workspace. Brand access dan permission mengikuti role user.</p>{!configured&&<div style={{background:"#fff7e8",color:"#855d14",padding:12,borderRadius:10,fontSize:12,lineHeight:1.5,marginBottom:14}}>Supabase belum dikonfigurasi. Auth guard otomatis nonaktif agar dashboard existing tidak terkunci.</div>}<label style={label}>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} style={input}/></label><label style={label}>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} style={input}/></label>{error&&<div style={{background:"#fff0f1",color:"#a3152d",padding:11,borderRadius:9,fontSize:12,marginTop:12}}>{error}</div>}<button disabled={loading||!configured} style={{width:"100%",marginTop:18,border:0,borderRadius:10,padding:"12px 14px",background:"#98142f",color:"white",fontWeight:800,cursor:"pointer",opacity:configured?1:.55}}>{loading?"Signing in...":"Sign In"}</button>{!configured&&<button type="button" onClick={()=>router.replace("/")} style={{width:"100%",marginTop:8,border:"1px solid #ddd4d8",borderRadius:10,padding:"11px 14px",background:"white",fontWeight:700,cursor:"pointer"}}>Continue in Local Mode</button>}</form></main>
}
const label:React.CSSProperties={display:"grid",gap:7,fontSize:12,fontWeight:700,marginTop:14};const input:React.CSSProperties={border:"1px solid #ddd4d8",borderRadius:10,padding:"11px 12px",fontSize:14,outline:"none"};
