"use client";

import { useEffect, useMemo, useState, type DragEvent } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, ArrowUp, ArrowDown, CalendarDays, CheckCircle2, Copy, ExternalLink, FileText, GripVertical, Pencil, Save, Sparkles, Trash2 } from "lucide-react";
import { loadBrief, loadCampaign, saveBrief, type BriefRecord, type BriefSection } from "@/lib/smm-workflow";
import "./page.css";

function formatDate(value?:string){if(!value)return"";return new Intl.DateTimeFormat("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date(`${value}T12:00:00`))}

export default function BriefPage(){
  const {id}=useParams<{id:string}>();
  const router=useRouter();
  const [brief,setBrief]=useState<BriefRecord|null>(null);
  const [editingId,setEditingId]=useState<string|null>(null);
  const [editDraft,setEditDraft]=useState<BriefSection|null>(null);
  const [draggingId,setDraggingId]=useState<string|null>(null);
  const [notes,setNotes]=useState("");
  const [improving,setImproving]=useState(false);
  const [scheduleOpen,setScheduleOpen]=useState(false);
  const [scheduleDate,setScheduleDate]=useState("");
  const [message,setMessage]=useState("");
  const [error,setError]=useState("");
  const [copied,setCopied]=useState(false);

  useEffect(()=>{const data=loadBrief(id);setBrief(data);if(!data)setError("Brief tidak ditemukan di browser storage.")},[id]);
  const campaignBundle=useMemo(()=>brief?loadCampaign(brief.campaign_id):null,[brief]);
  const researchCase=useMemo(()=>campaignBundle?.cases.find(item=>item.id===campaignBundle.ideas.find(idea=>idea.id===brief?.idea_id)?.research_case_id),[campaignBundle,brief]);
  const sources=researchCase?.mapped_sources??[];

  function persist(next:BriefRecord,msg?:string){setBrief(next);saveBrief(next);if(msg)setMessage(msg)}
  function invalidateQc(next:BriefRecord){return {...next,human_qc:"pending" as const,updated_at:new Date().toISOString()}}
  function beginEdit(section:BriefSection){setEditingId(section.id);setEditDraft({...section});setMessage("");setError("")}
  function saveSection(){if(!brief||!editDraft)return;const next=invalidateQc({...brief,sections:brief.sections.map(s=>s.id===editDraft.id?editDraft:s)});persist(next,"Section disimpan. Human QC perlu dilakukan ulang.");setEditingId(null);setEditDraft(null)}
  function removeSection(sectionId:string){if(!brief||!window.confirm("Hapus section ini?"))return;const sections=brief.sections.filter(s=>s.id!==sectionId).map((s,i)=>({...s,sequence_no:i+1}));persist(invalidateQc({...brief,sections}),"Section dihapus. Human QC perlu dilakukan ulang.")}
  function moveSection(sectionId:string,direction:-1|1){if(!brief)return;const index=brief.sections.findIndex(s=>s.id===sectionId);const target=index+direction;if(index<0||target<0||target>=brief.sections.length)return;const sections=[...brief.sections];const[moved]=sections.splice(index,1);sections.splice(target,0,moved);persist(invalidateQc({...brief,sections:sections.map((s,i)=>({...s,sequence_no:i+1}))}),"Urutan diperbarui. Human QC perlu dilakukan ulang.")}
  function dropSection(event:DragEvent<HTMLElement>,targetId:string){event.preventDefault();if(!brief)return;const sourceId=event.dataTransfer.getData("text/plain")||draggingId;if(!sourceId||sourceId===targetId)return;const source=brief.sections.findIndex(s=>s.id===sourceId),target=brief.sections.findIndex(s=>s.id===targetId);if(source<0||target<0)return;const sections=[...brief.sections];const[moved]=sections.splice(source,1);sections.splice(target,0,moved);persist(invalidateQc({...brief,sections:sections.map((s,i)=>({...s,sequence_no:i+1}))}),"Urutan drag & drop disimpan. Human QC perlu dilakukan ulang.");setDraggingId(null)}

  const fullText=useMemo(()=>{if(!brief)return"";return ["FINAL STORYTELLING BRIEF",`Brand: ${brief.brand_name}`,`Format: ${brief.recommended_format}`,`AI Quality: ${Math.round(brief.quality?.overall_score??0)}/100`,`Human QC: ${brief.human_qc.toUpperCase()}`,brief.scheduled_for?`Scheduled: ${formatDate(brief.scheduled_for)}`:"Scheduled: —","",`WORKING TITLE\n${brief.working_title}`,`\nEDITORIAL THESIS\n${brief.editorial_thesis}`,`\nCASE / EVIDENCE\n${brief.case_evidence}`,`\nCORE INSIGHT\n${brief.core_insight}`,`\nBRAND POV\n${brief.brand_pov}`,`\nSTORY SEQUENCE`,...brief.sections.flatMap(s=>[`\n${s.section_type.toUpperCase()} ${s.sequence_no} — ${s.purpose}`,`Headline: ${s.headline}`,`Copy: ${s.supporting_copy}`,`Evidence: ${s.evidence_needed}`,`Visual: ${s.visual_direction}`,`Transition: ${s.transition_to_next}`]),`\nFACT CHECK NOTES\n${brief.fact_check_notes}`,"\nSOURCES",...sources.map((s,i)=>`[S${i+1}] ${s.publisher} — ${s.title} — ${s.url}`)].join("\n")},[brief,sources]);
  async function copyBrief(){await navigator.clipboard.writeText(fullText);setCopied(true);setTimeout(()=>setCopied(false),1500)}
  function approveQc(){if(!brief)return;persist({...brief,human_qc:"approved",updated_at:new Date().toISOString()},"Human QC approved. Brief siap dijadwalkan.")}
  function openSchedule(){if(!brief)return;if(brief.human_qc!=="approved"){setError("Brief harus lolos Human QC sebelum dijadwalkan.");return}setScheduleDate(brief.scheduled_for||new Date().toISOString().slice(0,10));setScheduleOpen(true);setError("")}
  function saveSchedule(){if(!brief||!scheduleDate)return;persist({...brief,scheduled_for:scheduleDate,updated_at:new Date().toISOString()},`Brief dijadwalkan untuk ${formatDate(scheduleDate)}.`);setScheduleOpen(false)}
  function updateProduction(status:"draft"|"ready_to_design"|"designed"){if(!brief)return;persist({...brief,production_status:status,updated_at:new Date().toISOString()},`Production status: ${status.replaceAll("_"," ")}.`)}
  function updateDesignUrl(value:string){if(!brief)return;persist({...brief,design_url:value,updated_at:new Date().toISOString()})}
  async function improve(){if(!brief||!campaignBundle)return;setImproving(true);setError("");setMessage("");try{const response=await fetch("/api/ai/improve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brief,campaignBundle,notes})});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload?.ok)throw new Error(payload?.error||"Improve gagal.");if(payload.applied){persist(payload.brief as BriefRecord,`Brief diperbaiki dan re-scored menjadi ${Math.round(payload.score)}/100. Human QC perlu dilakukan ulang.`)}else setMessage(payload.message||"Versi lama dipertahankan karena score baru tidak lebih baik.")}catch(err){setError(err instanceof Error?err.message:"Improve gagal.")}finally{setImproving(false)}}

  if(!brief)return <main className="brief-page"><a className="brief-back" href="/content-generator"><ArrowLeft size={14}/> Quick Brief</a><div className="brief-empty">{error||"Loading brief..."}</div></main>;
  const score=Math.round(brief.quality?.overall_score??0);
  return <main className="brief-page">
    <div className="brief-toolbar"><button onClick={()=>router.push(`/campaign/${brief.campaign_id}`)}><ArrowLeft size={14}/> Story Angles</button><div><button onClick={copyBrief}><Copy size={14}/>{copied?"Copied ✓":"Copy Brief"}</button><button onClick={()=>window.print()}><FileText size={14}/> Print / PDF</button><button className="schedule-btn" onClick={openSchedule} disabled={brief.human_qc!=="approved"}><CalendarDays size={14}/>{brief.scheduled_for?"Ubah Jadwal":"Jadwalkan"}</button></div></div>
    {(message||error)&&<div className="brief-alerts">{message&&<div className="success">{message}</div>}{error&&<div className="error">{error}</div>}</div>}
    <section className="brief-hero"><div><p className="eyebrow">FINAL STORYTELLING BRIEF</p><h1>{brief.working_title}</h1><p>{brief.brand_name} · {brief.recommended_format} · {brief.target_audience}</p></div><div className={`quality-score ${score>=90?"good":score>=85?"warn":"bad"}`}><strong>{score}</strong><span>/100 AI Quality</span></div></section>
    <section className="brief-summary-grid">{[["Content Objective",brief.content_objective],["Editorial Thesis",brief.editorial_thesis],["Why This Case",brief.why_this_case],["Tension",brief.tension],["Core Insight",brief.core_insight],["Brand POV",brief.brand_pov],["Capability Bridge",brief.capability_bridge],["CTA",brief.cta]].map(([label,value])=><div key={label}><small>{label}</small><p>{value||"—"}</p></div>)}</section>
    <section className="brief-evidence"><small>CASE EVIDENCE</small><p>{brief.case_evidence}</p></section>
    <section className="qc-card"><div><div className="qc-title"><span>HUMAN QUALITY CONTROL</span><b className={brief.human_qc==="approved"?"approved":"pending"}>{brief.human_qc==="approved"?"QC Approved ✓":"Belum QC"}</b>{brief.scheduled_for&&<b className="scheduled">{formatDate(brief.scheduled_for)}</b>}</div><h2>Final check sebelum masuk kalender.</h2><p>Setiap perubahan pada section otomatis mengembalikan status QC menjadi pending.</p></div><div>{brief.human_qc!=="approved"?<button className="dark-action" onClick={approveQc}><CheckCircle2 size={15}/> Tandai Lolos Human QC</button>:<button className="primary" onClick={openSchedule}><CalendarDays size={15}/> {brief.scheduled_for?"Ubah Jadwal":"Jadwalkan Brief"}</button>}</div></section>
    <section className="production-card"><div><p className="eyebrow">DESIGN PRODUCTION</p><h2>Production Status & Design File</h2></div><div className="production-controls"><select value={brief.production_status||"draft"} onChange={e=>updateProduction(e.target.value as "draft"|"ready_to_design"|"designed")}><option value="draft">Draft</option><option value="ready_to_design">Ready to Design</option><option value="designed">Designed</option></select><div className="design-url"><input value={brief.design_url||""} onChange={e=>updateDesignUrl(e.target.value)} placeholder="Canva / Drive / design file URL"/>{brief.design_url&&<a href={brief.design_url} target="_blank" rel="noreferrer"><ExternalLink size={14}/></a>}</div></div></section>
    <section className="sequence-head"><div><p className="eyebrow">DESIGNER-READY · HUMAN EDITABLE</p><h2>Story Sequence ({brief.sections.length})</h2><p>Drag & drop, gunakan ↑ ↓, edit copy/evidence/visual/transition, atau hapus section.</p></div></section>
    <section className="brief-sections">{brief.sections.map((section,index)=>{const editing=editingId===section.id&&editDraft;return <article key={section.id} className={draggingId===section.id?"dragging":""} draggable={!editingId} onDragStart={e=>{setDraggingId(section.id);e.dataTransfer.setData("text/plain",section.id)}} onDragOver={e=>e.preventDefault()} onDrop={e=>dropSection(e,section.id)}><div className="section-top"><div><GripVertical size={15}/><span>{section.section_type} {section.sequence_no}</span><b>{section.purpose}</b></div><div><button disabled={index===0||Boolean(editingId)} onClick={()=>moveSection(section.id,-1)}><ArrowUp size={14}/></button><button disabled={index===brief.sections.length-1||Boolean(editingId)} onClick={()=>moveSection(section.id,1)}><ArrowDown size={14}/></button>{!editing&&<button onClick={()=>beginEdit(section)}><Pencil size={14}/></button>}<button onClick={()=>removeSection(section.id)}><Trash2 size={14}/></button></div></div>{editing?<div className="section-edit"><label>Purpose<input value={editDraft.purpose} onChange={e=>setEditDraft({...editDraft,purpose:e.target.value})}/></label><label>Headline<textarea value={editDraft.headline} onChange={e=>setEditDraft({...editDraft,headline:e.target.value})}/></label><label>Body Copy<textarea value={editDraft.supporting_copy} onChange={e=>setEditDraft({...editDraft,supporting_copy:e.target.value})}/></label><div><label>Evidence<textarea value={editDraft.evidence_needed} onChange={e=>setEditDraft({...editDraft,evidence_needed:e.target.value})}/></label><label>Visual Direction<textarea value={editDraft.visual_direction} onChange={e=>setEditDraft({...editDraft,visual_direction:e.target.value})}/></label></div><label>Transition<textarea value={editDraft.transition_to_next} onChange={e=>setEditDraft({...editDraft,transition_to_next:e.target.value})}/></label><div className="edit-actions"><button onClick={()=>{setEditingId(null);setEditDraft(null)}}>Batal</button><button className="primary" onClick={saveSection}><Save size={14}/> Simpan Section</button></div></div>:<><h3>{section.headline}</h3><p className="section-copy">{section.supporting_copy}</p><div className="section-detail"><div><small>EVIDENCE</small><p>{section.evidence_needed||"—"}</p></div><div><small>VISUAL DIRECTION</small><p>{section.visual_direction||"—"}</p></div><div><small>TRANSITION</small><p>{section.transition_to_next||"—"}</p></div></div></>}</article>})}</section>
    <section className="brief-bottom"><div className="sources-card"><h2>Fact Check & Sources</h2><p>{brief.fact_check_notes}</p>{sources.map((source,index)=><a key={source.url} href={source.url} target="_blank" rel="noreferrer"><small>[S{index+1}] {source.publisher}</small><strong>{source.title}</strong><span>{source.fact_notes}</span></a>)}</div><div className="improve-card"><p className="eyebrow">IMPROVE WITH AI</p><h2>Perbaiki hanya bagian yang lemah.</h2><p>AI membaca brief, quality review, dan source evidence. Versi baru hanya diterapkan jika score tidak turun.</p>{brief.quality?.reviewer_notes&&<div className="review-note">{brief.quality.reviewer_notes}</div>}<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Opsional: perkuat Slide 4-5, jangan ubah hook, CTA lebih soft..."/><button onClick={improve} disabled={improving}><Sparkles size={15}/>{improving?"Improving & re-scoring...":"Improve Brief with AI"}</button></div></section>
    {scheduleOpen&&<div className="schedule-modal"><div><div className="modal-head"><div><p className="eyebrow">CONTENT CALENDAR</p><h2>Jadwalkan Brief</h2></div><button onClick={()=>setScheduleOpen(false)}>✕</button></div><p>Pilih tanggal publikasi. Setelah masuk Calendar, jadwal dapat dipindahkan lagi.</p><input type="date" value={scheduleDate} onChange={e=>setScheduleDate(e.target.value)}/><div className="modal-actions"><button onClick={()=>setScheduleOpen(false)}>Batal</button><button className="primary" onClick={saveSchedule} disabled={!scheduleDate}>Simpan ke Calendar</button></div></div></div>}
  </main>;
}
