import {NextResponse} from "next/server";

export const dynamic="force-dynamic";

function bearer(request:Request){const value=request.headers.get("authorization")||"";return value.toLowerCase().startsWith("bearer ")?value.slice(7).trim():""}
function config(){return{url:process.env.NEXT_PUBLIC_SUPABASE_URL||"",anon:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"",service:process.env.SUPABASE_SERVICE_ROLE_KEY||""}}
async function validate(request:Request){const{url,anon}=config();const token=bearer(request);if(!url||!anon||!token)return null;const response=await fetch(`${url}/auth/v1/user`,{headers:{apikey:anon,Authorization:`Bearer ${token}`},cache:"no-store"});if(!response.ok)return null;return response.json().catch(()=>null)}
function serviceHeaders(){const{service}=config();return{apikey:service,Authorization:`Bearer ${service}`,"Content-Type":"application/json"}}

export async function GET(request:Request){const user=await validate(request);if(!user?.id)return NextResponse.json({ok:false,error:"Session login tidak valid."},{status:401});const{url,service}=config();if(!url||!service)return NextResponse.json({ok:false,error:"Task service belum dikonfigurasi."},{status:500});const response=await fetch(`${url}/rest/v1/workspace_tasks?select=*&order=updated_at.desc&limit=1000`,{headers:serviceHeaders(),cache:"no-store"});const payload=await response.json().catch(()=>[]);if(!response.ok)return NextResponse.json({ok:false,error:payload?.message||"Gagal membaca task."},{status:502});return NextResponse.json({ok:true,tasks:Array.isArray(payload)?payload:[]})}

export async function POST(request:Request){const user=await validate(request);if(!user?.id)return NextResponse.json({ok:false,error:"Session login tidak valid."},{status:401});const{url,service}=config();if(!url||!service)return NextResponse.json({ok:false,error:"Task service belum dikonfigurasi."},{status:500});const task=await request.json().catch(()=>null);if(!task?.id||!task?.brand_id||!task?.title)return NextResponse.json({ok:false,error:"Payload task tidak lengkap."},{status:400});const response=await fetch(`${url}/rest/v1/workspace_tasks?on_conflict=id`,{method:"POST",headers:{...serviceHeaders(),Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(task),cache:"no-store"});const payload=await response.json().catch(()=>null);if(!response.ok)return NextResponse.json({ok:false,error:payload?.message||"Gagal menyimpan task."},{status:502});return NextResponse.json({ok:true,task:Array.isArray(payload)?payload[0]:payload})}

export async function DELETE(request:Request){const user=await validate(request);if(!user?.id)return NextResponse.json({ok:false,error:"Session login tidak valid."},{status:401});const{url,service}=config();if(!url||!service)return NextResponse.json({ok:false,error:"Task service belum dikonfigurasi."},{status:500});const id=new URL(request.url).searchParams.get("id")?.trim();if(!id)return NextResponse.json({ok:false,error:"Task id wajib tersedia."},{status:400});const response=await fetch(`${url}/rest/v1/workspace_tasks?id=eq.${encodeURIComponent(id)}`,{method:"DELETE",headers:{...serviceHeaders(),Prefer:"return=minimal"},cache:"no-store"});if(!response.ok){const payload=await response.json().catch(()=>null);return NextResponse.json({ok:false,error:payload?.message||"Gagal menghapus task."},{status:502})}return NextResponse.json({ok:true})}
